---
# Run all tests
stages:
  - deployment test

before_script:
  - ansible --version
  - molecule --version

variables:
  GET_SOURCES_ATTEMPTS: "5"

AWS role cookiecutter:
  variables:
    AWS_REGION: us-east-1
  stage: deployment test
  script:
    - cookiecutter -f --no-input https://github.com/lean-delivery/ansible-development-kit --checkout feature/EPMLDI-1804-customize-volume-size-aws
    - mkdir -p ansible-role-default_role/molecule/resources/provisioning/
    - mv AWS ansible-role-default_role/molecule/resources/provisioning/
    - cd ansible-role-default_role
    - molecule test -s cloud-aws-direct
  tags:
    - aws

.AZURE role cookiecutter:
  stage: deployment test
  script:
    - cookiecutter -f --no-input https://github.com/lean-delivery/ansible-development-kit
    - mkdir -p ansible-role-default_role/molecule/resources/provisioning/
    - mv AZURE ansible-role-default_role/molecule/resources/provisioning/
    - cd ansible-role-default_role
    - molecule test -s cloud-azure-direct
  tags:
    - azure

.EPC role from cookiecutter test:
  variables:
    EPC_REGION: EPAM-BY2
  stage: deployment test
  script:
    - cookiecutter -f --no-input https://github.com/lean-delivery/ansible-development-kit
    - mkdir -p ansible-role-default_role/molecule/resources/provisioning/
    - mv EPC ansible-role-default_role/molecule/resources/provisioning/
    - cd ansible-role-default_role
    - molecule test -s cloud-epc-delegated
  tags:
    - delegated
